all				:	getint_zero.o ptr_arr.o linesort.o
getint_zero.o	:	getint_zero.c
	gcc -o getint_zero.o getint_zero.c
ptr_arr.o		:	ptr_arr.c
	gcc -o ptr_arr.o ptr_arr.c
linesort.o		:	linesort.c
	gcc -o linesort.o linesort.c